create table if not exists public.testimonies (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  title text not null,
  description text not null default '',
  video_url text,
  video_source text not null default 'url'
    check (video_source in ('upload', 'url')),
  thumbnail_url text,
  thumbnail_alt_text text not null default '',
  summary text not null default '',
  full_story text not null default '',
  image_url text,
  video_id text,
  service_id text not null default 'trauma-recovery',
  event_id uuid,
  display_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.testimonies
  add column if not exists id bigint generated by default as identity,
  add column if not exists name text not null default 'Community Story',
  add column if not exists role text not null default 'Community Story',
  add column if not exists title text not null default 'Untitled story',
  add column if not exists description text not null default '',
  add column if not exists video_url text,
  add column if not exists video_source text not null default 'url',
  add column if not exists thumbnail_url text,
  add column if not exists thumbnail_alt_text text not null default '',
  add column if not exists summary text not null default '',
  add column if not exists full_story text not null default '',
  add column if not exists image_url text,
  add column if not exists video_id text,
  add column if not exists service_id text not null default 'trauma-recovery',
  add column if not exists event_id uuid,
  add column if not exists display_order integer not null default 0,
  add column if not exists published boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.testimonies
  alter column video_url drop not null;
alter table public.testimonies
  alter column published set default true;

create index if not exists testimonies_published_order_idx
  on public.testimonies (published, display_order);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null,
  date text not null,
  location text not null default '',
  description text not null default '',
  cover_image_url text,
  gallery jsonb not null default '[]'::jsonb,
  service_id text not null
    check (service_id in ('trauma-recovery', 'practical-support', 'financial-support', 'community-building')),
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (service_id, slug)
);

create index if not exists events_service_published_date_idx
  on public.events (service_id, published, date);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'testimonies_service_id_check'
  ) then
    alter table public.testimonies
      add constraint testimonies_service_id_check
      check (service_id in ('trauma-recovery', 'practical-support', 'financial-support', 'community-building'));
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'testimonies_event_id_fkey'
  ) then
    alter table public.testimonies
      add constraint testimonies_event_id_fkey
      foreign key (event_id) references public.events(id) on delete set null;
  end if;
end $$;

insert into public.events (
  title, slug, date, location, description, service_id, published
)
select
  'SHEMA Visit to Kulda Community',
  'shema-visit-to-kulda-community',
  '2025-07-06',
  'Kulda Community',
  'Food and non-food items distributed with counseling support to households affected by insurgency.',
  'practical-support',
  true
where not exists (
  select 1 from public.events
  where title = 'SHEMA Visit to Kulda Community'
    and service_id = 'practical-support'
);

insert into public.events (
  title, slug, date, location, description, service_id, published
)
select
  'Widows Support Program',
  'widows-support-program',
  '',
  'Gombi 1 Primary School',
  '',
  'financial-support',
  true
where not exists (
  select 1 from public.events
  where title = 'Widows Support Program'
    and service_id = 'financial-support'
);

create index if not exists testimonies_service_event_published_idx
  on public.testimonies (service_id, event_id, published, display_order);

update public.testimonies
set summary = description
where summary = '';

update public.testimonies
set service_id = 'trauma-recovery'
where name = 'Widows Support Program'
  and title = 'Finding Hope After Crisis';

update public.testimonies
set service_id = 'practical-support'
where name = 'SHEMA Visit to Kulda Community'
  and title = 'Humanitarian Support in Kulda';

update public.testimonies
set event_id = (
  select id from public.events
  where title = 'Widows Support Program'
    and service_id = 'financial-support'
  limit 1
)
where video_url = 'https://pltuxx4q1i7colum.public.blob.vercel-storage.com/1001484421.mp4'
  and event_id is null;

update public.testimonies
set event_id = (
  select id from public.events
  where title = 'SHEMA Visit to Kulda Community'
    and service_id = 'practical-support'
  limit 1
)
where video_url = 'https://pltuxx4q1i7colum.public.blob.vercel-storage.com/1c9cfbfb-89f0-47db-a9bd-385f08435cb3.mov'
  and event_id is null;

update public.testimonies
set video_id = (regexp_match(
  video_url,
  '(?:youtube(?:-nocookie)?\.com/(?:watch\?.*?v=|embed/|shorts/|live/)|youtu\.be/)([A-Za-z0-9_-]{11})',
  'i'
))[1]
where video_id is null
  and video_url ~* '(youtube(?:-nocookie)?\.com|youtu\.be)';

insert into public.testimonies (
  name, role, title, description, summary, video_url, video_id, video_source,
  thumbnail_url, service_id, event_id, display_order, published
)
select
  'Widows Support Program',
  'Widows Support Program',
  'Finding Hope After Crisis',
  'Widows celebrating SHEMA''s visit and ongoing support.',
  'Widows celebrating SHEMA''s visit and ongoing support.',
  'https://pltuxx4q1i7colum.public.blob.vercel-storage.com/1001484421.mp4',
  null,
  'url',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1001069628.jpg-8cYMLLBTQKctxoncjb3a6MnAcFQxvK.jpeg',
  'financial-support',
  (
    select id from public.events
    where title = 'Widows Support Program'
      and service_id = 'financial-support'
    limit 1
  ),
  1,
  true
where not exists (
  select 1 from public.testimonies
  where video_url = 'https://pltuxx4q1i7colum.public.blob.vercel-storage.com/1001484421.mp4'
);

insert into public.testimonies (
  name, role, title, description, summary, video_url, video_id, video_source,
  thumbnail_url, service_id, event_id, display_order, published
)
select
  'SHEMA Visit to Kulda Community',
  'Community Outreach',
  'Humanitarian Support in Kulda',
  'SHEMA visited Kulda — an area affected by Boko Haram insurgency — assessing needs and providing practical aid to affected families.',
  'SHEMA visited Kulda — an area affected by Boko Haram insurgency — assessing needs and providing practical aid to affected families.',
  'https://pltuxx4q1i7colum.public.blob.vercel-storage.com/1c9cfbfb-89f0-47db-a9bd-385f08435cb3.mov',
  null,
  'url',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1001117168.jpg-ie0qZ4nXD5wy0CTxkT8lmhe9yg0zTK.jpeg',
  'practical-support',
  (
    select id from public.events
    where title = 'SHEMA Visit to Kulda Community'
      and service_id = 'practical-support'
    limit 1
  ),
  2,
  true
where not exists (
  select 1 from public.testimonies
  where video_url = 'https://pltuxx4q1i7colum.public.blob.vercel-storage.com/1c9cfbfb-89f0-47db-a9bd-385f08435cb3.mov'
);
